[funny_messages]
respect_previous_creators = [
	['text', 'I usually tend to ignore or blow others away but my master told me to be polite to you specifically Mr. Noam. So I will be polite and tell you that I have only one master and that is not you :). You have a great day now! I will be ignoring messages now.']
]
